// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv'
import { defineConfig } from 'prisma/config'

// Load .env first, then .env.local (which overrides)
config({ path: '.env' })
config({ path: '.env.local' })

// Determine which database URL to use for migrations
const getDatabaseUrl = (): string => {
  // For prod migrations, use PROD_DATABASE_URL
  if (process.env.MIGRATE_PROD === 'true') {
    const url = process.env.PROD_DATABASE_URL
    if (!url) throw new Error('PROD_DATABASE_URL is not set')
    return url
  }
  // For local: prefer direct connection URL, fallback to pooled
  const url = process.env.DATABASE_MIGRATION_URL || process.env.DATABASE_URL
  if (!url) throw new Error('DATABASE_URL is not set')
  return url
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: getDatabaseUrl(),
  },
})
