// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig, env } from 'prisma/config'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Use DATABASE_MIGRATION_URL for migrations (direct connection on port 5432)
    // Otherwise use DATABASE_URL for regular app connections (can use pooled connection on port 6543)
    url: process.env.DATABASE_MIGRATION_URL || env('DATABASE_URL'),
  },
})
